[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql", "php82Extensions.fileinfo", "php82Extensions.gd"]

[phases.install]
cmds = [" composer install --no-dev --prefer-dist --no-interaction --no-scripts --ignore-platform-reqs"]

[phases.build]
cmds = []

[start]
cmd = "php scripts/railway_setup.php && php -S 0.0.0.0:$PORT -t ."
