<?php
// Front controller for the PHP built-in server (`php -S ... router.php`),
// which is what runs in Docker and on Railway.
//
// Apache reads .htaccess; the built-in server does not. Without this router a
// deployment would happily serve /.env and /database/schema.sql as plain text.
// Everything .htaccess protects is enforced here as well, so both hosts behave
// the same way.

$path = parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH) ?? '/';
$rel  = ltrim(rawurldecode($path), '/');

if ($rel === '') {
    $rel = 'index.php';
}

$segments = explode('/', $rel);

/** Refuse the request without revealing whether the file exists. */
$deny = static function (): bool {
    http_response_code(404);
    header('Content-Type: text/html; charset=utf-8');
    require __DIR__ . '/404.php';
    return true;
};

// 1. No dotfiles anywhere in the path — .env, .git, .htaccess, and also ".."
//    so this doubles as traversal protection.
foreach ($segments as $segment) {
    if ($segment !== '' && $segment[0] === '.') {
        return $deny();
    }
}

// 2. Server-side only directories. These are require()d by the app; nothing in
//    them should ever be fetched over HTTP.
$privateDirs = ['config', 'database', 'scripts', 'includes', 'design', 'docs'];
if (in_array(strtolower($segments[0]), $privateDirs, true)) {
    return $deny();
}

// 3. Build and tooling manifests at the project root.
$privateFiles = [
    'composer.json', 'composer.lock', 'package.json', 'package-lock.json',
    'dockerfile', 'docker-compose.yml', 'docker-entrypoint.sh', 'procfile',
    'railway.json', 'router.php', 'setup.bat', 'setup.sh', 'license',
];
if (in_array(strtolower($rel), $privateFiles, true)) {
    return $deny();
}

// 4. Uploaded files are user-controlled: serve them, never execute them.
if (str_starts_with(strtolower($rel), 'assets/uploads/')
    && preg_match('/\.(php|phtml|phar|phps|php\d?)$/i', $rel)) {
    return $deny();
}

// 5. Search engines expect /sitemap.xml; the file is generated by PHP.
if (strtolower($rel) === 'sitemap.xml') {
    require __DIR__ . '/sitemap.php';
    return true;
}

$full = __DIR__ . '/' . $rel;

// 6. Real file — hand back to the server, which executes .php and streams
//    static assets with correct MIME types.
if (is_file($full)) {
    return false;
}

// 7. Directory with an index — same.
if (is_dir($full) && is_file(rtrim($full, '/') . '/index.php')) {
    return false;
}

// 8. Nothing matched: branded 404 instead of the server's bare error page.
return $deny();
